### ISSUE TITLE
fix hacky help autocomplete workaround in test

### ISSUE THREAD

**Issue by jan-vcapgemini** [devonfw/IDEasy#188]
See: 
https://github.com/devonfw/IDEasy/blob/b2754e933b89db43d9a661f451691b469c12672b/cli/src/test/java/com/devonfw/tools/ide/completion/CompleteTest.java#L104-L110

**Comment by hohwille** [comment]
@jan-vcapgemini thanks for clarifying this story. Now I get what is "hacky" and should be improved.
However, the problem is that we have a `VersionCommandlet` that prints the IDEasy version and it can be invoked via `--version` or `-v` what totally makes sense.
The problem is that the `help` prints the version of the commandlets what is `--version` for this one so `-v` is not included in the list of commandlets what somehow also makes sense.
Therefore, I do not have a very great idea how to improve this?
I prefect "hacky" stuff in test code rather than in the main code. Also I do not see that there is something wrong in the help output itself.

So would you suggest to add a `boolean` parameter to `getExpectedCandidates` that decides if `-v` is added or not so we do not later have to remove it? Or would that still be `hacky`?

**Comment by slskiba** [comment]
As discussed with @jan-vcapgemini, we deemed your suggestion to be fully sufficient. I made a PR to add the alias of `--version` via boolean parameter in `getExpectedCandidates`
