### ISSUE TITLE
CI Build fails in GitHub

### ISSUE THREAD

**Issue by aBega2000** [devonfw/IDEasy#209]
### Expected behavior

We want the CI build to run successfully in Github, so that everything can work properly

### Actual behavior

The CI build fails and there is an error in the tests, namely:

[ERROR]   InstallCommandletTest.setUp:34 » FatalStartup java.lang.RuntimeException: java.io.IOException: Failed to bind to /0.0.0.0:1111

### Comments/Hints:

It seems like there is an error with WireMock, when we try to bind to port 1111 in the URLs. 
First a Quick Fix will be implemented, then a generally more reliable solution will be found and implemented

**Comment by hohwille** [comment]
Reopening: We have only applied a quickfix (hack) with PR #210 so our CI gets green again.
However, we need to find a real solution:
* [This commit](https://github.com/devonfw/IDEasy/pull/210/commits/dcbece25c443edc1b245fa1285e9a98358fe9fda) is a brute hack to make it work that needs to be fixed properly.
* We should not use wiremock on different fixed ports in different tests and then end up with already allocated ports if tests run in parallel, etc. Either we can reduce everything to a single wiremock test (I guess that will not be possible) or we need to prevent that wiremock tests can run in parallel during the build or we need to make wiremock chose a free random port and then somehow inject that random port-number into the test-case to derive the correct download URL using that port rather than hardcoding it.

**Comment by hohwille** [comment]
IMHO this issue is already fixed with PR #238 etc.
