### ISSUE TITLE
backup() method fails to move directories

### ISSUE THREAD

**Issue by mvomiero** [devonfw/IDEasy#230]
### Expected behavior

if I have already a version of a tool installed in `devonfw/software/` and I want to install another one, IDEasy should move the current tool installation directory to `devonfw/updates/backup/` trough the method `FileAccessImpl.backup()`

### Actual behavior

Works good for symlinks but not for directories like ` java/` or `mvn/`: an exception is thrown, `java.lang.IllegalStateException: Failed to move`

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

Example: java

From `cli/`:

1.  make sure you have java installed or install it: 
    `devon mvn exec:java -Dexec.mainClass="com.devonfw.tools.ide.cli.Ideasy" -Dexec.args="--debug install java"
`

2.  install now another version (e.g. 17.0.2_8):
     `devon mvn exec:java -Dexec.mainClass="com.devonfw.tools.ide.cli.Ideasy" -Dexec.args="--debug install java 17.0.2_8"
`

3. Output:

  
<img width="878" alt="Capture" src="https://github.com/devonfw/IDEasy/assets/102261609/ee434b1a-be69-424d-b9c7-af151d0e2714">

**_NOTE: you will have to delete JAVA_VERSION from `devonfw/settings/ide.properties` if you want to run java again, otherwise you will keep getting the Failed to move exception_**

    

## Related/Dependent Issues

#225 was caused by the same method but here is actually another situation, since it's a directory and not a symlink.

### Affected version:

* OS: Windows and Linux, still not tested on Mac

**Comment by mvomiero** [comment]
Probably the problem is just because ideasy is using java itself so can't move the installation folder

**Comment by hohwille** [comment]
What you are seeing here is the famous Windows File Locking "bug".
Windows has the habit to lock files if they are in used. So if you start java in the `software/java/bin/java.exe` (e.g. you launch your IntelliJ or Eclipse or have a long maven process running) that folder gets locked by Windows and cannot be deleted until the lock is returned what by default only happens when the process holding the lock ends.
https://github.com/devonfw/ide/blob/master/documentation/advanced-tooling-windows.asciidoc#cope-with-file-locks

As the new IDEasy will only use symlinks/junctions the problem you are reporting is a known bug that already exists in devonfw-ide. So I would consider to close this as wontfix. However, before doing so we should improve the error handling.
We can catch the `AccessDeniedException` and if we are on Windows convert it to a new exception with more details giving the hint to the user that the file is most probably locked by windows (e.g. with a link to the according documentation, see link above but needs to be ported to IDEasy).

**Comment by hohwille** [comment]
Also for the symlink/junction we need to test if windows still creates file-locks preventing us from changing the link target (deleting the link and creating a new link to a different tool version folder).
I assume that this is the case and in such case a simple solution could be that `SystemPath` would resolve the link target instead of putting the link source path on the PATH.

**Comment by hohwille** [comment]
So to summarize:
* [x] Major file locking bug is created as #264 
* [ ] for this issue we can IMHO only improve the error reporting as suggested 3 comments above.
