### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by hohwille** [devonfw/IDEasy#245]
As a IDEasy user, I want to be able to use the product in any environment including ones that require an HTTP proxy server so that I am not locked out in such case and the product becomes useless.

By default you have direct internet access. However, there are various different restricted environments possible that require VPNs or HTTP proxy servers. Sometimes software developers have to even switch between environments that have different setups:
* home office
* company network
* customer network (for consultants)

With IDEasy we have implemented our own download for software packages using Java HTTP Client.
I am unsure if this already supports a download via an HTTP proxy by passing JVM arguments (`-D....proxy=...`) or not.
We have to analyze what needs to be done in the code and via configuration to make it work in such case.
The most common standard is using [environment variables](https://superuser.com/questions/944958/are-http-proxy-https-proxy-and-no-proxy-environment-variables-standard):
```
export http_proxy="http://proxy.server.name.company.com:80"
```

Before with `curl` it could be solved with config in a `~/.curlrc` e.g.
```
echo proxy="http://proxy.server.name.company.com:80" >> ~/.curlrc
```
(port 80 is just an example like the hostname)

Also for git some tweaks are required:
```
git config --global http.https://github.com.proxy http://proxy.server.name.company.com:80
```

In the worst case this leads to TLS issues as VPN and or proxy can interfere.
A hackish and bad solution is this one:
```
git config --global http.https://github.com.sslverify false
```

The clean solution is to download the company certificate and configure it to your truststore.

Further, in some cases even login and password may be required by HTTP proxy to access internet.

Besides making it work at all and having some documentation on the topic, a perfect solution would be allowing to configuring different profiles with names (e.g. `home`, `company`, `customer`) and then having the ability to switch between this profiles with a single command (e.g. `ide proxy set «profile»`). Another idea could be to install a small local HTTP proxy software that can do all this and always configure this globally on your system so all HTTP traffic is routed via that local proxy (say `http://localhost:80`) and then in that software you could again configure such profiles and then toggle there so we do not have to reinvent the wheel in IDEasy. I have not researched if some software exists that servers all our demands out of the box but most likely there is.

ATTENTION: This is a more advanced story that should be addressed in separate steps:
0. create a setup where you have a local HTTP proxy on your machine and can see if traffic flows via that proxy (see e.g. https://www.telerik.com/fiddler) . This opens the door for testing that IDEasy works with all traffic going via this proxy or not.
1. research how to make proxy configurable for our Java HttpClient in IDEasy and make it work on all platforms with our native image (e.g. `ideasy.exe` on Windows, `ideasy` on Linux/Mac). Document the results.
2. if needed make a PR to make this configurable in IDEasy (better).
3. Consider creating some automation (script, commandlet, ...) that can configure an HTTP proxy for all tools (IDEasy, git, Maven, Eclipse, IntelliJ, etc.)
4. research how a proxy and network profile switching could be realized

**Comment by mvomiero** [comment]
# 0. Research 

the purpose of this comment is to show the results of the first research - brainstorming phase of this issue (point 0 on the list).

After downloading and setting up Fiddler (that creates a proxy on 127.0.0.1:8888) and tracking the traffic, we can observe:

## java http Client

requests from java Http Client are currently not automatically detected from Fiddler. Is it possible though to explicitly specify a proxy, requests will then be detected.
Here in `FileAccessImpl`

```diff
- client = HttpClient.newBuilder().followRedirects(Redirect.ALWAYS).build();
+ client = HttpClient.newBuilder().proxy(ProxySelector.of(new InetSocketAddress("127.0.0.1", 8888)).build();
```

There should be a method to detect and get the system proxy, e.g. `Proxy proxy = getDefaultProxy();` but for me it never worked, it always returns null, even if the env variables `HTTP_PROXY`, `HTTPS_PROXY`, `http_proxy`, `https_proxy` are set. I researched about it online and all the solutions I saw ended specifying the proxy in the java code (solution above), seems to be a java http client problem, but I could research further if we plan to work with env variables. 

Note that Fiddler for example doesn't automatically set these variables so they have to be manually exported.

### curl

To compare the behavior of http client with the env variables I used curl. Normal requests with curl aren't detected from Fiddler either, if the env proxy variables mentioned above are set, they are automatically detected though. 

### Java JVM arguments

* adding arguments java -D... works, the requests are detected by fiddler

```bash
java -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=8888 HTTPSRequestExample
```
_My question would be: when would we use this approach? when we run the java commandlet or when compiling the native image e.g. `ideasy.exe`?_

## git

* do we really want to change the global configuration of git? shouldn't it be the task of the user or the user company - organization?

If the problem is about the internal git use of ideasy (e.g. cloning the repos `ide-urls` or `ide -settings`) we could just add the following arguments to redirect the request to the proxy (e.g. Fiddler). 
```
-c http.proxy=http://127.0.0.1:8888
```
(with the current state git requests are not detected by Fiddler).

## next steps

### 1. configure Java `HttpClient` in IDEasy

We saw it is possible, now the question is how we do it
* Do we introduce profiles or a specific commandlet?
* Or maybe just a variable in `ide.properties` for now?
* should we make some architecture choice first? like if we want to use env variables or a proxy server would be a different approach


#### different profiles vs proxy software?

we surely have to research more but this is my first opinion about the topic:

* I think that developing different profiles would require some work but would be feasible to integrate in IDEasy since is possible to set a proxy for java http client. Maybe would be more difficult to configure all the other services like mvn, git, eclipse, intellij etc.

* I researched a bit but not too deeply about a proxy software, for what I saw the only possibility is to have a proxy server...don't know if it would be too complicated. And if we have the problem that http client bypasses the proxy maybe it would do that for the proxy server?
I have not enough knowledge or experience in the field to really express a complete opinion.

@hohwille

**Comment by hohwille** [comment]
@mvomiero thanks for your research. This is already very valuable input.
In the section `java http Client` you are more or less saying that Java HTTP client does not support proxy unless we implement something in our code.
However, some lines below in `Java JVM arguments` you are saying that Java does support proxy if you provide the configuration as JVM argument (System property).
So if that works (also in our graalVM native image), then we have an easy solution:
https://github.com/devonfw/IDEasy/blob/bd09ce4b82e387cc323a2cb996eada7c0dd86e6a/cli/src/main/package/bin/ide#L3
Here, we can simply add the following:
```
if [ -n "${http_proxy}" ]; then
  _IDEASY="${_IDEASY} -Dhttp.proxyHost=${http_proxy}"
fi
```
Could you test this?
BTW: Please also consider other proxy beyond `http_proxy` related variables as well, if you later create a PR for this.
Then we would have a solution for our own downloads.
For IDEs like Eclipse and IntelliJ this will still be a different story...
