### ISSUE TITLE
Refactoring IntelliJ and android-studio

### ISSUE THREAD

**Issue by ndemirca** [devonfw/IDEasy#339]
Refactor the code by identifying the common implementations of the tool commandlets "IntelliJ" and "android-studio" and remove duplicates

**Comment by hohwille** [comment]
PR #339 was merged but this is not really completed:
* [ ] Introduce an abstract class `IdeaBasedIdeToolCommandlet` between `IdeToolCommandlet` and its current implementations `Intellij` and `AndroidStudio`. There might come support for additional such IDEs to IDEasy in the future (PyCharm, WebStorm, etc.).
* [ ] Extract common functionalities to the new abstract base class. 
  * [ ] IMHO plugin installation is the same for all IDEA/JetBrains IDEs except for some parameterization of the download URL and the IDE folder name in the plugins folder.
  * [ ] `IDEA_PROPERTIES` mechanism is the same for all IDEA/JetBrains IDEs only the name of the environment variable differs. The Variable value differs per workspace. Therefore setting it once in postInstall with a fixed workspace name is buggy. We need to "export" this property via ProcessContext for each call of that IDE. Also it seems an existing flaw that we use the same-filename for different IDE products: See [android-studio](https://github.com/devonfw/ide-settings/blob/main/android-studio/workspace/update/idea.properties) and [IntelliJ](https://github.com/devonfw/ide-settings/blob/main/intellij/workspace/update/idea.properties). As both files have different content, they also must have different filenames as otherwise one overrides the other.
  * [ ] The `getBinaryName()` problem is the same for all IDEA/JetBrains IDEs. The current solution is still not nice. I would prefer a postInstall hook that creates a simple wrapper bash script if the default command is not already present. So create bash script `studio` that only calls `studio64.exe $*`, etc.
