### ISSUE TITLE
Uninstall graalvm is not successful, fails to find installed version

### ISSUE THREAD

**Issue by slskiba** [devonfw/IDEasy#395]
### Expected behavior

As a end user, I want to uninstall graalvm using the `uninstall graalvm` command.

### Actual behavior

graalvm is still present and fully functional after running `uninstall graalvm`. 
![image](https://github.com/devonfw/IDEasy/assets/161473135/1aed2df5-9a23-455b-b138-d3ec362be8c1)

### Steps to reproduce (windows)

1. `install graalvm`
2. `uninstall graalvm`

**Comment by hohwille** [comment]
My assumption is that uninstall is implemented in a generic way and just removes `software/«tool»`.
Since we have and exceptional situation for GraalVM that installs to `software/extra/graalvm` this does not work.
Current code:
https://github.com/devonfw/IDEasy/blob/b870e36e93d32c51ba0e5f1f429456a2791b09a8/cli/src/main/java/com/devonfw/tools/ide/commandlet/UninstallCommandlet.java#L43-L53

As always the proper solution is delegation to the according tool and have that default implementation in `ToolCommandlet`. Then `GraalVm` commandlet can override this method as needed.

**Comment by hohwille** [comment]
See `InstallCommandlet` that properly delegates to the tool:
https://github.com/devonfw/IDEasy/blob/b870e36e93d32c51ba0e5f1f429456a2791b09a8/cli/src/main/java/com/devonfw/tools/ide/commandlet/InstallCommandlet.java#L49
