### ISSUE TITLE
Show "cygwin is not supported" message for cygwin users

### ISSUE THREAD

**Issue by jan-vcapgemini** [devonfw/IDEasy#715]
As a `cygwin` user I expect IDEasy to show me that this program does not work properly on `cygwin` and I have to use `bash` instead.
Adjust documentation accordingly.

**Comment by hohwille** [comment]
We could even add a link to some documentation page on github. There we could even document some tips and tricks to make IDEasy work with cygwin.
However, the official status is we recommend everybody to use git-bash and stop using cygwin but we do not want to block usage of cygwin. The user can symlink his `.bashrc` from his regular home directory to its cygwin home directory and the same for its `.ide` folder. But we do not plan any automatic process for that since cygwin caused us lots of pointless headaches in devonfw-ide where all is working smooth with git-bash.
